/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.ControleAluno;
import controle.ControleCurso;
import controle.ControleDisciplina;
import controle.IControleCadastro;
import java.util.HashMap;
import modelo.Curso;
import modelo.Docente;
import util.DialogBoxUtils;

/**
 *
 * @author Administrador
 */
public class TelaCadastroDisciplina extends TelaCadastro {

    /**
     * Creates new form TelaCadastroDisciplina
     */
    private ControleCurso controleCurso;
    
    public TelaCadastroDisciplina(IControleCadastro controle) {
        super(controle);
        initComponents();
        setLocationRelativeTo(null);
        inicializarComponentesTela();
    }
    
    public ControleCurso getControleCurso() {
        return controleCurso;
    }
    
    public void inicializarComponentesTela() {
        jT_Disciplina.setText("");
        jS_crgHoraria.setValue(2000);
        jS_semestre.setValue(6);
        ControleDisciplina controleCurso = (ControleDisciplina) controle;
        for (String nomeCurso : controleCurso.getControleCurso().getNomesCursos()) {
            jC_cursos.addItem(nomeCurso);
        }
        jC_cursos.setSelectedIndex(0);
    }
    
    public void setarDadosTela(HashMap<String, Object> dados) {
        if (dados == null || dados.isEmpty()) {
            DialogBoxUtils.exibirMensagemDeErro("Erro", "Erro ao setar dados na tela");
        }

        jT_Disciplina.setText((String) dados.getOrDefault("disciplina", ""));
        jS_crgHoraria.setValue(dados.getOrDefault("crghoraria", 0));
        jS_semestre.setValue(dados.getOrDefault("semestre", 0));
        if (dados.get("curso") != null) {
            jC_cursos.setSelectedItem(((Curso) dados.get("curso")).getNome());
        }
    }
    
    @Override
    public HashMap<String, Object> getDadosTela() {
        HashMap<String, Object> dados = new HashMap<>();
        dados.put("disciplina", jT_Disciplina.getText());
        dados.put("crghoraria", jS_crgHoraria.getValue());
        dados.put("semestre", jS_semestre.getValue());
        int indexCurso = jC_cursos.getSelectedIndex() - 1;
        if (indexCurso >= 0) {
            dados.put("curso", ((ControleDisciplina) controle).getControleCurso().getCursoSelecionado(indexCurso));
        } else {
            dados.put("curso", null);
        }
        return dados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT_Disciplina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jS_crgHoraria = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jS_semestre = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jC_cursos = new javax.swing.JComboBox<>();
        jB_salvar = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(231, 243));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Disciplina");
        jLabel1.setMaximumSize(new java.awt.Dimension(129, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(129, 17));
        jLabel1.setPreferredSize(new java.awt.Dimension(129, 17));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Disciplina");
        jLabel2.setMaximumSize(new java.awt.Dimension(26, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(26, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 18));

        jT_Disciplina.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Carga Horaria");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 18));

        jS_crgHoraria.setMinimumSize(new java.awt.Dimension(100, 22));
        jS_crgHoraria.setName(""); // NOI18N
        jS_crgHoraria.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Semestre");
        jLabel4.setMaximumSize(new java.awt.Dimension(64, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(64, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 18));

        jS_semestre.setMinimumSize(new java.awt.Dimension(100, 22));
        jS_semestre.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Curso");
        jLabel5.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 18));

        jC_cursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Curso" }));
        jC_cursos.setMinimumSize(new java.awt.Dimension(152, 22));
        jC_cursos.setPreferredSize(new java.awt.Dimension(152, 22));

        jB_salvar.setBackground(java.awt.SystemColor.activeCaption);
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_cancelar.setBackground(java.awt.SystemColor.controlHighlight);
        jB_cancelar.setText("Cancelar");
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_salvar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jS_crgHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jS_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jC_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jT_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS_crgHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jC_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_salvar)
                    .addComponent(jB_cancelar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        if (!editarDados) {
            controle.salvar(getDadosTela());
        } else {
            controle.editar(getDadosTela());
        }
        controle.atualizarTabelaTelaListagem();
        setVisible(false);
    }//GEN-LAST:event_jB_salvarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JComboBox<String> jC_cursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jS_crgHoraria;
    private javax.swing.JSpinner jS_semestre;
    private javax.swing.JTextField jT_Disciplina;
    // End of variables declaration//GEN-END:variables
}
